import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  template: `
    <p>
      input-button-unit works!
      The title is: {{ title }}
    </p>

    <input [value]="generateTitle()">

    {{ generateTitle() }}
    <button>Save</button>
  `,
  styleUrls: ['./input-button-unit.component.scss']
})
export class InputButtonUnitComponent implements OnInit{
  title = 'Hello World';

  changeTitle(newTitle: string) {
    console.log(newTitle);
    this.title = newTitle;
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }
  constructor() {
    console.log('in constructor');
    this.changeTitle('My First Angular App');
    console.log(this.title);
  }

  ngOnInit(): void {
    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);
  }
}
